[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.lifecycle]
  onPreBuild = "npm install --force"
